# Copyright 2017-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=7

inherit cargo git-r3

DESCRIPTION="Binaries for testing the Cranelift libraries"
HOMEPAGE="https://github.com/CraneStation/cranelift"

RESTRICT="mirror"
LICENSE="apache-2.0-with-llvm-exception"
SLOT="0"
KEYWORDS="~amd64"
IUSE="cpu_flags_x86_sse2 test"

EGIT_REPO_URI="https://github.com/CraneStation/cranelift.git"

DEPEND=">=virtual/rust-1.37.0"
RDEPEND=""
REQUIRED_USE="x86? ( cpu_flags_x86_sse2 )"

S="${WORKDIR}"/cranelift-${PV}

src_unpack() {
        if [[ "${PV}" == *9999* ]]; then
                git-r3_src_unpack
                cargo_live_src_unpack
        else
                cargo_src_unpack
        fi
}

src_configure() {
	# Do nothing
	echo "Configuring cranelift..."
}

src_compile() {
	export CARGO_HOME="${ECARGO_HOME}"
	cargo build -j$(makeopts_jobs) --release || die
}

src_test() {
	export RUST_BACKTRACE=1
	cargo test --all -j$(makeopts_jobs) || die "tests failed"
}

src_install() {
	dobin target/release/clif-util
}
