# Copyright 2017-2019 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.1.5

EAPI=8

CRATES="
	backtrace-0.3.44
	backtrace-sys-0.1.32
	bitflags-1.2.1
	cargo-xbuild-0.5.35
	cargo_metadata-0.9.1
	cc-1.0.50
	cfg-if-0.1.10
	cloudabi-0.0.3
	error-chain-0.12.0
	error-chain-0.12.2
	fs2-0.4.3
	getrandom-0.1.14
	itoa-0.4.5
	lazy_static-1.4.0
	libc-0.2.67
	lock_api-0.3.3
	parking_lot-0.10.0
	parking_lot_core-0.7.0
	ppv-lite86-0.2.8
	proc-macro2-1.0.8
	quote-1.0.2
	rand-0.7.3
	rand_chacha-0.2.2
	rand_core-0.5.1
	rand_hc-0.2.0
	redox_syscall-0.1.56
	remove_dir_all-0.5.2
	rustc-demangle-0.1.16
	rustc_version-0.2.3
	ryu-1.0.2
	same-file-1.0.6
	scopeguard-1.1.0
	semver-0.9.0
	semver-parser-0.7.0
	serde-1.0.104
	serde_derive-1.0.104
	serde_json-1.0.48
	smallvec-1.2.0
	syn-1.0.14
	tempfile-3.1.0
	toml-0.5.6
	unicode-xid-0.2.0
	version_check-0.9.1
	walkdir-2.3.1
	wasi-0.9.0+wasi-snapshot-preview1
	winapi-0.3.8
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.3
	winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Automatically cross-compiles the sysroot crates core, compiler_builtins, and alloc."
HOMEPAGE="https://github.com/rust-osdev/cargo-xbuild"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="|| ( MIT Apache-2.0 )"
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
