# Copyright 2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.5.0

EAPI=8

CRATES="
	anyhow-1.0.33
	cargo_metadata-0.11.4
	cargo-xbuild-0.6.6
	cfg-if-0.1.10
	getrandom-0.1.15
	itoa-0.4.6
	libc-0.2.79
	ppv-lite86-0.2.9
	proc-macro2-1.0.24
	quote-1.0.7
	rand-0.7.3
	rand_chacha-0.2.2
	rand_core-0.5.1
	rand_hc-0.2.0
	redox_syscall-0.1.57
	remove_dir_all-0.5.3
	rustc_version-0.2.3
	ryu-1.0.5
	same-file-1.0.6
	semver-0.9.0
	semver-0.10.0
	semver-parser-0.7.0
	serde-1.0.116
	serde_derive-1.0.116
	serde_json-1.0.59
	syn-1.0.44
	tempfile-3.1.0
	toml-0.5.7
	unicode-xid-0.2.1
	walkdir-2.3.1
	wasi-0.9.0+wasi-snapshot-preview1
	winapi-0.3.9
	winapi-i686-pc-windows-gnu-0.4.0
	winapi-util-0.1.5
	winapi-x86_64-pc-windows-gnu-0.4.0
"

inherit cargo

DESCRIPTION="Automatically cross-compiles the sysroot crates core, compiler_builtins, and alloc."
# Double check the homepage as the cargo_metadata crate
# does not provide this value so instead repository is used
HOMEPAGE="https://github.com/rust-osdev/cargo-xbuild"
SRC_URI="$(cargo_crate_uris)"
# License set may be more restrictive as OR is not respected
# use cargo-license for a more accurate license picture
LICENSE="Apache-2.0 Apache-2.0-with-LLVM-exceptions Boost-1.0 MIT Unlicense"
SLOT="0"
KEYWORDS="~amd64"
